var subjectElement;
var subject;
var studentElement;
var studentFullName;
var studentFirstName;
var studentLastName;
var gradeElement;
var grade;
var newExam;
var item;
var itemName;
var itemRight;
var itemValue;
var itemDelete;
var itemButton;
var buttonX;
var studentNode;
var studentGrade;
var addBtn = document.querySelector(".add-btn");
var passedCountElement = document.querySelector(".exam-passed-count");
var failedCountElement = document.querySelector(".exam-failed-count");
var failedPercentageElement = document.querySelector(".exam-failed-percentage");
var countPass = 0;
var countFail = 0;
var percentageFail = 0;
var totalStudents = 0;
var totalStudentsElement = document.querySelector(".exam-total");
var passedList = document.querySelector(".passed-list");
var failedList = document.querySelector(".failed-list");